services:
  analyzer:
    build: .
    container_name: freelance_analyzer
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
      LLM_MODEL: ${LLM_MODEL}
      EMBEDDING_MODEL: ${EMBEDDING_MODEL}
      CHROMA_PERSIST_DIR: /app/chroma_data
      API_KEY: ${API_KEY}
    volumes:
      - chroma_data:/app/chroma_data
    networks:
      - freelance_network

volumes:
  chroma_data:
networks:
  freelance_network:
    # Указываем, что сеть уже существует (ее создал парсер)
    external: true
    name: freelance_network