"""create order_analyses

Revision ID: 003f8c27248e
Revises: 
Create Date: 2026-09-07 19:04:41.215113

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "003f8c27248e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_analyses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("is_relevant", sa.Boolean(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("category_confidence", sa.Float(), nullable=True),
        sa.Column("questions", sa.JSON(), nullable=True),
        sa.Column("popularity_score", sa.Float(), nullable=True),
        sa.Column("estimated_demand", sa.String(length=20), nullable=True),
        sa.Column("avg_response_time_days", sa.Float(), nullable=True),
        sa.Column("analyzed_at", sa.TIMESTAMP(), server_default="NOW()", nullable=True),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
    )
    op.alter_column("orders", "is_taken", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_index(op.f("ix_external_id_site"), table_name="orders")
    op.drop_index(op.f("ix_is_taken"), table_name="orders")
    op.drop_index(op.f("ix_published_at"), table_name="orders")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_published_at"), "orders", ["published_at"], unique=False)
    op.create_index(op.f("ix_is_taken"), "orders", ["is_taken"], unique=False)
    op.create_index(
        op.f("ix_external_id_site"), "orders", ["site_name", "external_id"], unique=True
    )
    op.alter_column("orders", "is_taken", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_table("order_analyses")
    # ### end Alembic commands ###
